# Generated by Django 3.2.7 on 2021-11-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='person_used',
            field=models.CharField(default='dont know', max_length=30),
        ),
        migrations.AlterField(
            model_name='todo',
            name='amount',
            field=models.FloatField(),
        ),
    ]
