# Generated by Django 3.2.7 on 2021-11-18 14:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0003_auto_20211118_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Costlist',
        ),
    ]
