# Generated by Django 3.2.7 on 2021-11-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_rename_todo_costlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costlist',
            name='user',
        ),
    ]
