# Generated by Django 3.2.7 on 2021-11-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_costlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costlist',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
