# Generated by Django 3.2.7 on 2021-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_alter_costlist_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costlist',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
