# Generated by Django 3.2.7 on 2021-11-24 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_alter_costlist_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='costlist',
            name='added_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costlist',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
